CLASS zcl_github_test DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_GITHUB_TEST IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.
    out->write( 'Hello, GitHub!!!' ).
  ENDMETHOD.
ENDCLASS.
